### ISSUE TITLE
Update linters.yaml to run linters on PR and push to main

### ISSUE THREAD

**Issue by jcadam14** [cfpb/regtech-mail-api#68]
Need to update the linters.yaml with the following:
```
on:
  pull_request:
  push:
    branches:
      - "main"
```
